#!/usr/bin/env python3
"""
Browly Packaging Script
=======================

This script packages Browly into standalone executables for macOS, Linux, and Windows
using PyInstaller. It handles platform-specific requirements and creates optimized
binaries for distribution.

Usage:
    python package.py              # Package for current platform
    python package.py --all         # Package for all platforms (requires wine for Windows)
    python package.py --mac         # Package for macOS only
    python package.py --linux       # Package for Linux only
    python package.py --windows     # Package for Windows only
    python package.py --clean       # Clean build artifacts
"""

import os
import sys
import subprocess
import platform
import shutil
from pathlib import Path
from typing import List, Dict, Optional


class Packager:
    def __init__(self):
        self.project_dir = Path(__file__).parent
        self.dist_dir = self.project_dir / "dist"
        self.build_dir = self.project_dir / "build"
        self.spec_dir = self.project_dir / "packaging"
        
        # Ensure directories exist
        self.spec_dir.mkdir(exist_ok=True)
        
        # Platform detection
        self.current_platform = platform.system().lower()
        self.is_mac = self.current_platform == "darwin"
        self.is_linux = self.current_platform == "linux"
        self.is_windows = self.current_platform == "windows"
    
    def run_command(self, cmd: List[str], cwd: Optional[Path] = None) -> bool:
        """Run a shell command and return success status."""
        try:
            print(f"Running: {' '.join(cmd)}")
            result = subprocess.run(
                cmd, 
                cwd=cwd or self.project_dir,
                check=True,
                capture_output=True,
                text=True
            )
            if result.stdout:
                print(result.stdout)
            if result.stderr:
                print(result.stderr, file=sys.stderr)
            return True
        except subprocess.CalledProcessError as e:
            print(f"Command failed: {' '.join(cmd)}")
            print(e.stderr, file=sys.stderr)
            return False
    
    def clean(self) -> bool:
        """Clean build artifacts."""
        print("🧹 Cleaning build artifacts...")
        
        # Remove dist and build directories
        for dir_path in [self.dist_dir, self.build_dir]:
            if dir_path.exists():
                shutil.rmtree(dir_path)
                print(f"Removed {dir_path}")
        
        # Remove spec files
        for spec_file in self.spec_dir.glob("*.spec"):
            spec_file.unlink()
            print(f"Removed {spec_file}")
        
        return True
    
    def create_spec_file(self, platform: str = None) -> Path:
        """Create a PyInstaller spec file for the given platform."""
        platform = platform or self.current_platform
        spec_name = f"browly_{platform}.spec"
        spec_path = self.spec_dir / spec_name
        
        print(f"📝 Creating spec file: {spec_name}")
        
        # Base spec content
        spec_content = f"""
# Browly PyInstaller Spec File
# Platform: {platform}
# Generated by package.py

block_cipher = None

"""
        
        # Add platform-specific content
        if platform == "darwin":  # macOS
            spec_content += self._get_mac_spec()
        elif platform == "linux":  # Linux
            spec_content += self._get_linux_spec()
        elif platform == "windows":  # Windows
            spec_content += self._get_windows_spec()
        else:
            spec_content += self._get_generic_spec()
        
        # Write spec file
        with open(spec_path, "w") as f:
            f.write(spec_content)
        
        return spec_path
    
    def _get_generic_spec(self) -> str:
        """Get generic spec content."""
        return """
a = Analysis(
    ['browly/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[('browly', 'browly')],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

ex = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='browly',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon=None,
)
"""
    
    def _get_mac_spec(self) -> str:
        """Get macOS-specific spec content."""
        return f"""
a = Analysis(
    ['browly/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[('browly', 'browly')],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

ex = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='browly',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon='browly/assets/mac_icon.icns',
)

app = BUNDLE(
    ex,
    name='Browly.app',
    icon='browly/assets/mac_icon.icns',
    bundle_identifier='com.browly.browserpicker',
)
"""
    
    def _get_linux_spec(self) -> str:
        """Get Linux-specific spec content."""
        return f"""
a = Analysis(
    ['browly/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[('browly', 'browly')],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

ex = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='browly',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon='browly/assets/linux_icon.png',
)
"""
    
    def _get_windows_spec(self) -> str:
        """Get Windows-specific spec content."""
        return f"""
a = Analysis(
    ['browly/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[('browly', 'browly')],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=True,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

ex = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='browly',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon='browly/assets/windows_icon.ico',
)
"""
    
    def package_current_platform(self) -> bool:
        """Package for the current platform."""
        print(f"📦 Packaging for {self.current_platform}...")
        
        # Create spec file
        spec_path = self.create_spec_file()
        
        # Install PyInstaller if not available
        try:
            import PyInstaller
        except ImportError:
            print("🔧 Installing PyInstaller...")
            if not self.run_command([sys.executable, "-m", "pip", "install", "pyinstaller"]):
                return False
        
        # Run PyInstaller
        cmd = ["pyinstaller", str(spec_path), "--clean"]
        
        if self.is_mac:
            cmd.extend(["--windowed", "--osx-bundle-identifier", "com.browly.browserpicker"])
        elif self.is_linux:
            cmd.extend(["--windowed"])
        elif self.is_windows:
            cmd.extend(["--windowed", "--noconfirm"])
        
        return self.run_command(cmd)
    
    def package_all_platforms(self) -> bool:
        """Package for all platforms (requires cross-compilation setup)."""
        print("🌍 Packaging for all platforms...")
        
        success = True
        
        # Current platform
        if not self.package_current_platform():
            success = False
        
        # Other platforms would require cross-compilation setup
        # For now, just package current platform
        
        return success
    
    def package_mac(self) -> bool:
        """Package for macOS."""
        if not self.is_mac:
            print("❌ macOS packaging requires macOS host")
            return False
        return self.package_current_platform()
    
    def package_linux(self) -> bool:
        """Package for Linux."""
        if not self.is_linux:
            print("❌ Linux packaging requires Linux host")
            return False
        return self.package_current_platform()
    
    def package_windows(self) -> bool:
        """Package for Windows."""
        if not self.is_windows:
            print("❌ Windows packaging requires Windows host or Wine")
            return False
        return self.package_current_platform()
    
    def create_assets_directory(self):
        """Create assets directory structure."""
        assets_dir = self.project_dir / "browly" / "assets"
        assets_dir.mkdir(parents=True, exist_ok=True)
        
        # Create placeholder icon files if they don't exist
        placeholder_icons = {
            "mac_icon.icns": "ICNS",
            "linux_icon.png": "PNG",
            "windows_icon.ico": "ICO"
        }
        
        for icon_file, icon_type in placeholder_icons.items():
            icon_path = assets_dir / icon_file
            if not icon_path.exists():
                # Create a simple placeholder icon
                print(f"🎨 Creating placeholder {icon_type} icon: {icon_file}")
                # In a real scenario, you'd have actual icon files here
                icon_path.touch()
    
    def create_distribution_archive(self, platform: str):
        """Create a zip/tar.gz archive of the distribution."""
        print(f"📦 Creating distribution archive for {platform}...")
        
        dist_path = self.dist_dir / "browly"
        if not dist_path.exists():
            print("❌ No distribution found to archive")
            return False
        
        # Determine archive format
        if platform == "windows":
            archive_name = f"browly-{platform}-x64.zip"
            archive_cmd = ["zip", "-r", archive_name, "browly"]
        else:
            archive_name = f"browly-{platform}-x64.tar.gz"
            archive_cmd = ["tar", "-czf", archive_name, "browly"]
        
        # Create archive
        return self.run_command(archive_cmd, cwd=self.dist_dir)
    
    def print_packaging_instructions(self):
        """Print instructions for manual packaging."""
        print("""
📋 Manual Packaging Instructions
=================================

1. Install PyInstaller:
   pip install pyinstaller

2. Package for current platform:
   pyinstaller --onefile --windowed --name browly browly/main.py

3. Platform-specific options:

   macOS:
   pyinstaller --windowed --name Browly --icon=icon.icns browly/main.py
   
   Linux:
   pyinstaller --onefile --windowed --name browly --icon=icon.png browly/main.py
   
   Windows:
   pyinstaller --onefile --windowed --name browly --icon=icon.ico browly/main.py

4. Advanced options:
   --upx-dir /path/to/upx      # Use UPX compression
   --exclude-module module   # Exclude unnecessary modules
   --hidden-import module    # Include hidden imports

5. Code signing (recommended for distribution):
   macOS: codesign --deep --force --verify --verbose --sign "Developer ID" dist/Browly.app
   Windows: signtool sign /fd SHA256 /a dist/browly.exe
""")


def main():
    """Main entry point for packaging script."""
    packager = Packager()
    
    # Parse command line arguments
    if len(sys.argv) > 1:
        if sys.argv[1] == "--clean":
            packager.clean()
            return
        elif sys.argv[1] == "--all":
            packager.package_all_platforms()
            return
        elif sys.argv[1] == "--mac":
            packager.package_mac()
            return
        elif sys.argv[1] == "--linux":
            packager.package_linux()
            return
        elif sys.argv[1] == "--windows":
            packager.package_windows()
            return
        elif sys.argv[1] in ["--help", "-h", "help"]:
            print(__doc__)
            return
    
    # Default: package current platform
    print("🚀 Starting Browly packaging process...")
    print(f"Platform: {packager.current_platform}")
    print(f"Python: {sys.version}")
    
    # Create assets directory
    packager.create_assets_directory()
    
    # Package for current platform
    if packager.package_current_platform():
        print("✅ Packaging completed successfully!")
        print(f"📁 Output directory: {packager.dist_dir}")
        
        # Create archive
        if packager.create_distribution_archive(packager.current_platform):
            archive_path = packager.dist_dir / f"browly-{packager.current_platform}-x64.tar.gz"
            if archive_path.exists():
                print(f"📦 Archive created: {archive_path}")
    else:
        print("❌ Packaging failed")
        packager.print_packaging_instructions()


if __name__ == "__main__":
    main()